// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvoVnPJQQGrkgDlhfifumjIBUsSaLEXWo',
    appId: '1:363551420024:web:f153bf77f1ca538d5d478d',
    messagingSenderId: '363551420024',
    projectId: 'floop-ad59e',
    authDomain: 'floop-ad59e.firebaseapp.com',
    storageBucket: 'floop-ad59e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD837rod4T7NwC0wag2HU8UnRci5OL1dJ0',
    appId: '1:363551420024:android:ed28b597743fa8865d478d',
    messagingSenderId: '363551420024',
    projectId: 'floop-ad59e',
    storageBucket: 'floop-ad59e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFCgtYq18STrCryUScsnXYaDI_8bc4d4',
    appId: '1:363551420024:ios:41089ca1864077825d478d',
    messagingSenderId: '363551420024',
    projectId: 'floop-ad59e',
    storageBucket: 'floop-ad59e.appspot.com',
    iosClientId: '363551420024-g50o6qpv67pppaq1ftjue1gr7abfti69.apps.googleusercontent.com',
    iosBundleId: 'com.example.floop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUFCgtYq18STrCryUScsnXYaDI_8bc4d4',
    appId: '1:363551420024:ios:41089ca1864077825d478d',
    messagingSenderId: '363551420024',
    projectId: 'floop-ad59e',
    storageBucket: 'floop-ad59e.appspot.com',
    iosClientId: '363551420024-g50o6qpv67pppaq1ftjue1gr7abfti69.apps.googleusercontent.com',
    iosBundleId: 'com.example.floop',
  );
}
